// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateScheduleOKCode is the HTTP code returned for type CreateScheduleOK
const CreateScheduleOKCode int = 200

/*CreateScheduleOK woot!

swagger:response createScheduleOK
*/
type CreateScheduleOK struct {
}

// NewCreateScheduleOK creates CreateScheduleOK with default headers values
func NewCreateScheduleOK() *CreateScheduleOK {

	return &CreateScheduleOK{}
}

// WriteResponse to the client
func (o *CreateScheduleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
