// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateScheduleHandlerFunc turns a function with the right signature into a create schedule handler
type CreateScheduleHandlerFunc func(CreateScheduleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateScheduleHandlerFunc) Handle(params CreateScheduleParams) middleware.Responder {
	return fn(params)
}

// CreateScheduleHandler interface for that can handle valid create schedule params
type CreateScheduleHandler interface {
	Handle(CreateScheduleParams) middleware.Responder
}

// NewCreateSchedule creates a new http.Handler for the create schedule operation
func NewCreateSchedule(ctx *middleware.Context, handler CreateScheduleHandler) *CreateSchedule {
	return &CreateSchedule{Context: ctx, Handler: handler}
}

/*CreateSchedule swagger:route POST /schedules createSchedule

get our recording schedules

*/
type CreateSchedule struct {
	Context *middleware.Context
	Handler CreateScheduleHandler
}

func (o *CreateSchedule) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateScheduleParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
