// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteContentOKCode is the HTTP code returned for type DeleteContentOK
const DeleteContentOKCode int = 200

/*DeleteContentOK woot!

swagger:response deleteContentOK
*/
type DeleteContentOK struct {
}

// NewDeleteContentOK creates DeleteContentOK with default headers values
func NewDeleteContentOK() *DeleteContentOK {

	return &DeleteContentOK{}
}

// WriteResponse to the client
func (o *DeleteContentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteContentNotFoundCode is the HTTP code returned for type DeleteContentNotFound
const DeleteContentNotFoundCode int = 404

/*DeleteContentNotFound not found

swagger:response deleteContentNotFound
*/
type DeleteContentNotFound struct {
}

// NewDeleteContentNotFound creates DeleteContentNotFound with default headers values
func NewDeleteContentNotFound() *DeleteContentNotFound {

	return &DeleteContentNotFound{}
}

// WriteResponse to the client
func (o *DeleteContentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteContentInternalServerErrorCode is the HTTP code returned for type DeleteContentInternalServerError
const DeleteContentInternalServerErrorCode int = 500

/*DeleteContentInternalServerError broke

swagger:response deleteContentInternalServerError
*/
type DeleteContentInternalServerError struct {
}

// NewDeleteContentInternalServerError creates DeleteContentInternalServerError with default headers values
func NewDeleteContentInternalServerError() *DeleteContentInternalServerError {

	return &DeleteContentInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteContentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
