// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteContentParams creates a new DeleteContentParams object
// no default values defined in spec.
func NewDeleteContentParams() DeleteContentParams {

	return DeleteContentParams{}
}

// DeleteContentParams contains all the bound params for the delete content operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteContent
type DeleteContentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	ContentName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteContentParams() beforehand.
func (o *DeleteContentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rContentName, rhkContentName, _ := route.Params.GetOK("content_name")
	if err := o.bindContentName(rContentName, rhkContentName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindContentName binds and validates parameter ContentName from path.
func (o *DeleteContentParams) bindContentName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ContentName = raw

	return nil
}
