// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteScheduleOKCode is the HTTP code returned for type DeleteScheduleOK
const DeleteScheduleOKCode int = 200

/*DeleteScheduleOK woot!

swagger:response deleteScheduleOK
*/
type DeleteScheduleOK struct {
}

// NewDeleteScheduleOK creates DeleteScheduleOK with default headers values
func NewDeleteScheduleOK() *DeleteScheduleOK {

	return &DeleteScheduleOK{}
}

// WriteResponse to the client
func (o *DeleteScheduleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteScheduleNotFoundCode is the HTTP code returned for type DeleteScheduleNotFound
const DeleteScheduleNotFoundCode int = 404

/*DeleteScheduleNotFound not found

swagger:response deleteScheduleNotFound
*/
type DeleteScheduleNotFound struct {
}

// NewDeleteScheduleNotFound creates DeleteScheduleNotFound with default headers values
func NewDeleteScheduleNotFound() *DeleteScheduleNotFound {

	return &DeleteScheduleNotFound{}
}

// WriteResponse to the client
func (o *DeleteScheduleNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteScheduleInternalServerErrorCode is the HTTP code returned for type DeleteScheduleInternalServerError
const DeleteScheduleInternalServerErrorCode int = 500

/*DeleteScheduleInternalServerError broke

swagger:response deleteScheduleInternalServerError
*/
type DeleteScheduleInternalServerError struct {
}

// NewDeleteScheduleInternalServerError creates DeleteScheduleInternalServerError with default headers values
func NewDeleteScheduleInternalServerError() *DeleteScheduleInternalServerError {

	return &DeleteScheduleInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteScheduleInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
