// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetContentFoldersOKCode is the HTTP code returned for type GetContentFoldersOK
const GetContentFoldersOKCode int = 200

/*GetContentFoldersOK woot!

swagger:response getContentFoldersOK
*/
type GetContentFoldersOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetContentFoldersOK creates GetContentFoldersOK with default headers values
func NewGetContentFoldersOK() *GetContentFoldersOK {

	return &GetContentFoldersOK{}
}

// WithPayload adds the payload to the get content folders o k response
func (o *GetContentFoldersOK) WithPayload(payload []string) *GetContentFoldersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get content folders o k response
func (o *GetContentFoldersOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContentFoldersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
