// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetContentFoldersHandlerFunc turns a function with the right signature into a get content folders handler
type GetContentFoldersHandlerFunc func(GetContentFoldersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetContentFoldersHandlerFunc) Handle(params GetContentFoldersParams) middleware.Responder {
	return fn(params)
}

// GetContentFoldersHandler interface for that can handle valid get content folders params
type GetContentFoldersHandler interface {
	Handle(GetContentFoldersParams) middleware.Responder
}

// NewGetContentFolders creates a new http.Handler for the get content folders operation
func NewGetContentFolders(ctx *middleware.Context, handler GetContentFoldersHandler) *GetContentFolders {
	return &GetContentFolders{Context: ctx, Handler: handler}
}

/*GetContentFolders swagger:route GET /content/folders getContentFolders

get existing content folders

*/
type GetContentFolders struct {
	Context *middleware.Context
	Handler GetContentFoldersHandler
}

func (o *GetContentFolders) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetContentFoldersParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
