// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ansoni/isakura-manager/models"
)

// GetContentOKCode is the HTTP code returned for type GetContentOK
const GetContentOKCode int = 200

/*GetContentOK woot!

swagger:response getContentOK
*/
type GetContentOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Content `json:"body,omitempty"`
}

// NewGetContentOK creates GetContentOK with default headers values
func NewGetContentOK() *GetContentOK {

	return &GetContentOK{}
}

// WithPayload adds the payload to the get content o k response
func (o *GetContentOK) WithPayload(payload []*models.Content) *GetContentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get content o k response
func (o *GetContentOK) SetPayload(payload []*models.Content) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Content, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
