// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ansoni/isakura-manager/models"
)

// GetChannelsGuideOKCode is the HTTP code returned for type GetChannelsGuideOK
const GetChannelsGuideOKCode int = 200

/*GetChannelsGuideOK woot!

swagger:response getChannelsGuideOK
*/
type GetChannelsGuideOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ChannelGuide `json:"body,omitempty"`
}

// NewGetChannelsGuideOK creates GetChannelsGuideOK with default headers values
func NewGetChannelsGuideOK() *GetChannelsGuideOK {

	return &GetChannelsGuideOK{}
}

// WithPayload adds the payload to the get channels guide o k response
func (o *GetChannelsGuideOK) WithPayload(payload []*models.ChannelGuide) *GetChannelsGuideOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get channels guide o k response
func (o *GetChannelsGuideOK) SetPayload(payload []*models.ChannelGuide) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChannelsGuideOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ChannelGuide, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
