// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUIContentHandlerFunc turns a function with the right signature into a get Ui content handler
type GetUIContentHandlerFunc func(GetUIContentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUIContentHandlerFunc) Handle(params GetUIContentParams) middleware.Responder {
	return fn(params)
}

// GetUIContentHandler interface for that can handle valid get Ui content params
type GetUIContentHandler interface {
	Handle(GetUIContentParams) middleware.Responder
}

// NewGetUIContent creates a new http.Handler for the get Ui content operation
func NewGetUIContent(ctx *middleware.Context, handler GetUIContentHandler) *GetUIContent {
	return &GetUIContent{Context: ctx, Handler: handler}
}

/*GetUIContent swagger:route GET /ui/{resource} getUiContent

app redirect

*/
type GetUIContent struct {
	Context *middleware.Context
	Handler GetUIContentHandler
}

func (o *GetUIContent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUIContentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
