// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ansoni/isakura-manager/models"
)

// GetSchedulesOKCode is the HTTP code returned for type GetSchedulesOK
const GetSchedulesOKCode int = 200

/*GetSchedulesOK woot!

swagger:response getSchedulesOK
*/
type GetSchedulesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Schedule `json:"body,omitempty"`
}

// NewGetSchedulesOK creates GetSchedulesOK with default headers values
func NewGetSchedulesOK() *GetSchedulesOK {

	return &GetSchedulesOK{}
}

// WithPayload adds the payload to the get schedules o k response
func (o *GetSchedulesOK) WithPayload(payload []*models.Schedule) *GetSchedulesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedules o k response
func (o *GetSchedulesOK) SetPayload(payload []*models.Schedule) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSchedulesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Schedule, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
