// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetChannelsHandlerFunc turns a function with the right signature into a get channels handler
type GetChannelsHandlerFunc func(GetChannelsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetChannelsHandlerFunc) Handle(params GetChannelsParams) middleware.Responder {
	return fn(params)
}

// GetChannelsHandler interface for that can handle valid get channels params
type GetChannelsHandler interface {
	Handle(GetChannelsParams) middleware.Responder
}

// NewGetChannels creates a new http.Handler for the get channels operation
func NewGetChannels(ctx *middleware.Context, handler GetChannelsHandler) *GetChannels {
	return &GetChannels{Context: ctx, Handler: handler}
}

/*GetChannels swagger:route GET /channels/ getChannels

get all channels

*/
type GetChannels struct {
	Context *middleware.Context
	Handler GetChannelsHandler
}

func (o *GetChannels) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetChannelsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
