// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSchedulesHandlerFunc turns a function with the right signature into a get schedules handler
type GetSchedulesHandlerFunc func(GetSchedulesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSchedulesHandlerFunc) Handle(params GetSchedulesParams) middleware.Responder {
	return fn(params)
}

// GetSchedulesHandler interface for that can handle valid get schedules params
type GetSchedulesHandler interface {
	Handle(GetSchedulesParams) middleware.Responder
}

// NewGetSchedules creates a new http.Handler for the get schedules operation
func NewGetSchedules(ctx *middleware.Context, handler GetSchedulesHandler) *GetSchedules {
	return &GetSchedules{Context: ctx, Handler: handler}
}

/*GetSchedules swagger:route GET /schedules getSchedules

get our recording schedules

*/
type GetSchedules struct {
	Context *middleware.Context
	Handler GetSchedulesHandler
}

func (o *GetSchedules) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSchedulesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
