// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetContentPreviewParams creates a new GetContentPreviewParams object
// no default values defined in spec.
func NewGetContentPreviewParams() GetContentPreviewParams {

	return GetContentPreviewParams{}
}

// GetContentPreviewParams contains all the bound params for the get content preview operation
// typically these are obtained from a http.Request
//
// swagger:parameters getContentPreview
type GetContentPreviewParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Channel string
	/*
	  Required: true
	  In: path
	*/
	Content string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetContentPreviewParams() beforehand.
func (o *GetContentPreviewParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rChannel, rhkChannel, _ := route.Params.GetOK("channel")
	if err := o.bindChannel(rChannel, rhkChannel, route.Formats); err != nil {
		res = append(res, err)
	}

	rContent, rhkContent, _ := route.Params.GetOK("content")
	if err := o.bindContent(rContent, rhkContent, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChannel binds and validates parameter Channel from path.
func (o *GetContentPreviewParams) bindChannel(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Channel = raw

	return nil
}

// bindContent binds and validates parameter Content from path.
func (o *GetContentPreviewParams) bindContent(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Content = raw

	return nil
}
