// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetRootRedirectMovedPermanentlyCode is the HTTP code returned for type GetRootRedirectMovedPermanently
const GetRootRedirectMovedPermanentlyCode int = 301

/*GetRootRedirectMovedPermanently woot!

swagger:response getRootRedirectMovedPermanently
*/
type GetRootRedirectMovedPermanently struct {
}

// NewGetRootRedirectMovedPermanently creates GetRootRedirectMovedPermanently with default headers values
func NewGetRootRedirectMovedPermanently() *GetRootRedirectMovedPermanently {

	return &GetRootRedirectMovedPermanently{}
}

// WriteResponse to the client
func (o *GetRootRedirectMovedPermanently) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(301)
}
