// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChannelsGuideParams creates a new GetChannelsGuideParams object
// no default values defined in spec.
func NewGetChannelsGuideParams() GetChannelsGuideParams {

	return GetChannelsGuideParams{}
}

// GetChannelsGuideParams contains all the bound params for the get channels guide operation
// typically these are obtained from a http.Request
//
// swagger:parameters getChannelsGuide
type GetChannelsGuideParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Search Param to filter on
	  In: query
	*/
	Search *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetChannelsGuideParams() beforehand.
func (o *GetChannelsGuideParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qSearch, qhkSearch, _ := qs.GetOK("search")
	if err := o.bindSearch(qSearch, qhkSearch, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSearch binds and validates parameter Search from query.
func (o *GetChannelsGuideParams) bindSearch(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Search = &raw

	return nil
}
