// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUIContentOKCode is the HTTP code returned for type GetUIContentOK
const GetUIContentOKCode int = 200

/*GetUIContentOK woot!

swagger:response getUiContentOK
*/
type GetUIContentOK struct {
}

// NewGetUIContentOK creates GetUIContentOK with default headers values
func NewGetUIContentOK() *GetUIContentOK {

	return &GetUIContentOK{}
}

// WriteResponse to the client
func (o *GetUIContentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
