// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetChannelGuideHandlerFunc turns a function with the right signature into a get channel guide handler
type GetChannelGuideHandlerFunc func(GetChannelGuideParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetChannelGuideHandlerFunc) Handle(params GetChannelGuideParams) middleware.Responder {
	return fn(params)
}

// GetChannelGuideHandler interface for that can handle valid get channel guide params
type GetChannelGuideHandler interface {
	Handle(GetChannelGuideParams) middleware.Responder
}

// NewGetChannelGuide creates a new http.Handler for the get channel guide operation
func NewGetChannelGuide(ctx *middleware.Context, handler GetChannelGuideHandler) *GetChannelGuide {
	return &GetChannelGuide{Context: ctx, Handler: handler}
}

/*GetChannelGuide swagger:route GET /channels/{channel}/guide getChannelGuide

get channel guide

*/
type GetChannelGuide struct {
	Context *middleware.Context
	Handler GetChannelGuideHandler
}

func (o *GetChannelGuide) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetChannelGuideParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
