// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewIsakuraManagerAPI creates a new IsakuraManager instance
func NewIsakuraManagerAPI(spec *loads.Document) *IsakuraManagerAPI {
	return &IsakuraManagerAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		VideoXFlvProducer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("videoXFlv producer has not yet been implemented")
		}),
		CreateScheduleHandler: CreateScheduleHandlerFunc(func(params CreateScheduleParams) middleware.Responder {
			return middleware.NotImplemented("operation CreateSchedule has not yet been implemented")
		}),
		DeleteContentHandler: DeleteContentHandlerFunc(func(params DeleteContentParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteContent has not yet been implemented")
		}),
		DeleteScheduleHandler: DeleteScheduleHandlerFunc(func(params DeleteScheduleParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteSchedule has not yet been implemented")
		}),
		GetChannelGuideHandler: GetChannelGuideHandlerFunc(func(params GetChannelGuideParams) middleware.Responder {
			return middleware.NotImplemented("operation GetChannelGuide has not yet been implemented")
		}),
		GetChannelsHandler: GetChannelsHandlerFunc(func(params GetChannelsParams) middleware.Responder {
			return middleware.NotImplemented("operation GetChannels has not yet been implemented")
		}),
		GetChannelsGuideHandler: GetChannelsGuideHandlerFunc(func(params GetChannelsGuideParams) middleware.Responder {
			return middleware.NotImplemented("operation GetChannelsGuide has not yet been implemented")
		}),
		GetContentHandler: GetContentHandlerFunc(func(params GetContentParams) middleware.Responder {
			return middleware.NotImplemented("operation GetContent has not yet been implemented")
		}),
		GetContentFoldersHandler: GetContentFoldersHandlerFunc(func(params GetContentFoldersParams) middleware.Responder {
			return middleware.NotImplemented("operation GetContentFolders has not yet been implemented")
		}),
		GetContentPreviewHandler: GetContentPreviewHandlerFunc(func(params GetContentPreviewParams) middleware.Responder {
			return middleware.NotImplemented("operation GetContentPreview has not yet been implemented")
		}),
		GetRootRedirectHandler: GetRootRedirectHandlerFunc(func(params GetRootRedirectParams) middleware.Responder {
			return middleware.NotImplemented("operation GetRootRedirect has not yet been implemented")
		}),
		GetSchedulesHandler: GetSchedulesHandlerFunc(func(params GetSchedulesParams) middleware.Responder {
			return middleware.NotImplemented("operation GetSchedules has not yet been implemented")
		}),
		GetUIContentHandler: GetUIContentHandlerFunc(func(params GetUIContentParams) middleware.Responder {
			return middleware.NotImplemented("operation GetUIContent has not yet been implemented")
		}),
	}
}

/*IsakuraManagerAPI Isakura-manager */
type IsakuraManagerAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json; charset=utf-8" mime type
	JSONProducer runtime.Producer
	// VideoXFlvProducer registers a producer for a "video/x-flv" mime type
	VideoXFlvProducer runtime.Producer

	// CreateScheduleHandler sets the operation handler for the create schedule operation
	CreateScheduleHandler CreateScheduleHandler
	// DeleteContentHandler sets the operation handler for the delete content operation
	DeleteContentHandler DeleteContentHandler
	// DeleteScheduleHandler sets the operation handler for the delete schedule operation
	DeleteScheduleHandler DeleteScheduleHandler
	// GetChannelGuideHandler sets the operation handler for the get channel guide operation
	GetChannelGuideHandler GetChannelGuideHandler
	// GetChannelsHandler sets the operation handler for the get channels operation
	GetChannelsHandler GetChannelsHandler
	// GetChannelsGuideHandler sets the operation handler for the get channels guide operation
	GetChannelsGuideHandler GetChannelsGuideHandler
	// GetContentHandler sets the operation handler for the get content operation
	GetContentHandler GetContentHandler
	// GetContentFoldersHandler sets the operation handler for the get content folders operation
	GetContentFoldersHandler GetContentFoldersHandler
	// GetContentPreviewHandler sets the operation handler for the get content preview operation
	GetContentPreviewHandler GetContentPreviewHandler
	// GetRootRedirectHandler sets the operation handler for the get root redirect operation
	GetRootRedirectHandler GetRootRedirectHandler
	// GetSchedulesHandler sets the operation handler for the get schedules operation
	GetSchedulesHandler GetSchedulesHandler
	// GetUIContentHandler sets the operation handler for the get Ui content operation
	GetUIContentHandler GetUIContentHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *IsakuraManagerAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *IsakuraManagerAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *IsakuraManagerAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *IsakuraManagerAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *IsakuraManagerAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *IsakuraManagerAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *IsakuraManagerAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the IsakuraManagerAPI
func (o *IsakuraManagerAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.VideoXFlvProducer == nil {
		unregistered = append(unregistered, "VideoXFlvProducer")
	}

	if o.CreateScheduleHandler == nil {
		unregistered = append(unregistered, "CreateScheduleHandler")
	}

	if o.DeleteContentHandler == nil {
		unregistered = append(unregistered, "DeleteContentHandler")
	}

	if o.DeleteScheduleHandler == nil {
		unregistered = append(unregistered, "DeleteScheduleHandler")
	}

	if o.GetChannelGuideHandler == nil {
		unregistered = append(unregistered, "GetChannelGuideHandler")
	}

	if o.GetChannelsHandler == nil {
		unregistered = append(unregistered, "GetChannelsHandler")
	}

	if o.GetChannelsGuideHandler == nil {
		unregistered = append(unregistered, "GetChannelsGuideHandler")
	}

	if o.GetContentHandler == nil {
		unregistered = append(unregistered, "GetContentHandler")
	}

	if o.GetContentFoldersHandler == nil {
		unregistered = append(unregistered, "GetContentFoldersHandler")
	}

	if o.GetContentPreviewHandler == nil {
		unregistered = append(unregistered, "GetContentPreviewHandler")
	}

	if o.GetRootRedirectHandler == nil {
		unregistered = append(unregistered, "GetRootRedirectHandler")
	}

	if o.GetSchedulesHandler == nil {
		unregistered = append(unregistered, "GetSchedulesHandler")
	}

	if o.GetUIContentHandler == nil {
		unregistered = append(unregistered, "GetUIContentHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *IsakuraManagerAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *IsakuraManagerAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *IsakuraManagerAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *IsakuraManagerAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *IsakuraManagerAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		case "video/x-flv":
			result["video/x-flv"] = o.VideoXFlvProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *IsakuraManagerAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the isakura manager API
func (o *IsakuraManagerAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *IsakuraManagerAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/schedules"] = NewCreateSchedule(o.context, o.CreateScheduleHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/content/{content_name}"] = NewDeleteContent(o.context, o.DeleteContentHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/schedules/{schedule_name}"] = NewDeleteSchedule(o.context, o.DeleteScheduleHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/channels/{channel}/guide"] = NewGetChannelGuide(o.context, o.GetChannelGuideHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/channels"] = NewGetChannels(o.context, o.GetChannelsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/channels/guide"] = NewGetChannelsGuide(o.context, o.GetChannelsGuideHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/content"] = NewGetContent(o.context, o.GetContentHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/content/folders"] = NewGetContentFolders(o.context, o.GetContentFoldersHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/channels/{channel}/content/{content}/preview"] = NewGetContentPreview(o.context, o.GetContentPreviewHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"][""] = NewGetRootRedirect(o.context, o.GetRootRedirectHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/schedules"] = NewGetSchedules(o.context, o.GetSchedulesHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/ui/{resource}"] = NewGetUIContent(o.context, o.GetUIContentHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *IsakuraManagerAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *IsakuraManagerAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *IsakuraManagerAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *IsakuraManagerAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
