// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ChannelSummary channel summary
// swagger:model ChannelSummary
type ChannelSummary struct {

	// channel name
	ChannelName string `json:"channelName,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this channel summary
func (m *ChannelSummary) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChannelSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChannelSummary) UnmarshalBinary(b []byte) error {
	var res ChannelSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
