// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Content content
// swagger:model Content
type Content struct {

	// download date
	// Format: date-time
	DownloadDate strfmt.DateTime `json:"download_date,omitempty"`

	// local path
	LocalPath string `json:"local_path,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this content
func (m *Content) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDownloadDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Content) validateDownloadDate(formats strfmt.Registry) error {

	if swag.IsZero(m.DownloadDate) { // not required
		return nil
	}

	if err := validate.FormatOf("download_date", "body", "date-time", m.DownloadDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Content) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Content) UnmarshalBinary(b []byte) error {
	var res Content
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
