// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Guide guide
// swagger:model Guide
type Guide struct {

	// airdate
	// Format: date-time
	Airdate strfmt.DateTime `json:"airdate,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this guide
func (m *Guide) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAirdate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Guide) validateAirdate(formats strfmt.Registry) error {

	if swag.IsZero(m.Airdate) { // not required
		return nil
	}

	if err := validate.FormatOf("airdate", "body", "date-time", m.Airdate.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Guide) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Guide) UnmarshalBinary(b []byte) error {
	var res Guide
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
